/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StenIconAaC {
        /**
          * 传入的class名称
         */
        "classNames": string;
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 旋转的角度
         */
        "rotate": number;
        /**
          * icon 尺寸 默认 20
         */
        "size": number | string;
        /**
          * 是否自动旋转
         */
        "spin": boolean;
        /**
          * styles 传入的css样式
         */
        "styles": object;
    }
    interface StenIconAdd {
        /**
          * 传入的class名称
         */
        "classNames": string;
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 旋转的角度
         */
        "rotate": number;
        /**
          * icon 尺寸 默认 20
         */
        "size": number | string;
        /**
          * 是否自动旋转
         */
        "spin": boolean;
        /**
          * styles 传入的css样式
         */
        "styles": object;
    }
    interface StenIconAddImage {
        /**
          * 传入的class名称
         */
        "classNames": string;
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 旋转的角度
         */
        "rotate": number;
        /**
          * icon 尺寸 默认 20
         */
        "size": number | string;
        /**
          * 是否自动旋转
         */
        "spin": boolean;
        /**
          * styles 传入的css样式
         */
        "styles": object;
    }
    interface StenIconAddUser {
        /**
          * 传入的class名称
         */
        "classNames": string;
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 旋转的角度
         */
        "rotate": number;
        /**
          * icon 尺寸 默认 20
         */
        "size": number | string;
        /**
          * 是否自动旋转
         */
        "spin": boolean;
        /**
          * styles 传入的css样式
         */
        "styles": object;
    }
    interface StenIconAlertCloseCollapse {
        /**
          * 传入的class名称
         */
        "classNames": string;
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 旋转的角度
         */
        "rotate": number;
        /**
          * icon 尺寸 默认 20
         */
        "size": number | string;
        /**
          * 是否自动旋转
         */
        "spin": boolean;
        /**
          * styles 传入的css样式
         */
        "styles": object;
    }
    interface StenIconAlertErrorC {
        /**
          * 传入的class名称
         */
        "classNames": string;
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 旋转的角度
         */
        "rotate": number;
        /**
          * icon 尺寸 默认 20
         */
        "size": number | string;
        /**
          * 是否自动旋转
         */
        "spin": boolean;
        /**
          * styles 传入的css样式
         */
        "styles": object;
    }
    interface StenIconAlertErrorCircleC {
        /**
          * 传入的class名称
         */
        "classNames": string;
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 旋转的角度
         */
        "rotate": number;
        /**
          * icon 尺寸 默认 20
         */
        "size": number | string;
        /**
          * 是否自动旋转
         */
        "spin": boolean;
        /**
          * styles 传入的css样式
         */
        "styles": object;
    }
    interface StenIcons {
        /**
          * 传入的class名称
         */
        "classNames": string;
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 旋转的角度
         */
        "rotate": number;
        /**
          * icon 尺寸 默认 20
         */
        "size": number | string;
        /**
          * 是否自动旋转
         */
        "spin": boolean;
        /**
          * styles 传入的css样式
         */
        "styles": object;
    }
    interface StenImage {
        /**
          * Prop 错误文案
         */
        "errorText": string;
        /**
          * Prop fit 图片填充格式
         */
        "fit": 'none' | 'contain' | 'cover' | 'fill' | 'scale-down';
        /**
          * Prop lazy 是否懒加载
         */
        "lazy": boolean;
        /**
          * Prop placeholder 加载文案
         */
        "placeholder": string;
        /**
          * Prop src 图片链接
         */
        "src": string;
    }
    interface StenTest {
        "add": () => Promise<void>;
    }
}
declare global {
    interface HTMLStenIconAaCElement extends Components.StenIconAaC, HTMLStencilElement {
    }
    var HTMLStenIconAaCElement: {
        prototype: HTMLStenIconAaCElement;
        new (): HTMLStenIconAaCElement;
    };
    interface HTMLStenIconAddElement extends Components.StenIconAdd, HTMLStencilElement {
    }
    var HTMLStenIconAddElement: {
        prototype: HTMLStenIconAddElement;
        new (): HTMLStenIconAddElement;
    };
    interface HTMLStenIconAddImageElement extends Components.StenIconAddImage, HTMLStencilElement {
    }
    var HTMLStenIconAddImageElement: {
        prototype: HTMLStenIconAddImageElement;
        new (): HTMLStenIconAddImageElement;
    };
    interface HTMLStenIconAddUserElement extends Components.StenIconAddUser, HTMLStencilElement {
    }
    var HTMLStenIconAddUserElement: {
        prototype: HTMLStenIconAddUserElement;
        new (): HTMLStenIconAddUserElement;
    };
    interface HTMLStenIconAlertCloseCollapseElement extends Components.StenIconAlertCloseCollapse, HTMLStencilElement {
    }
    var HTMLStenIconAlertCloseCollapseElement: {
        prototype: HTMLStenIconAlertCloseCollapseElement;
        new (): HTMLStenIconAlertCloseCollapseElement;
    };
    interface HTMLStenIconAlertErrorCElement extends Components.StenIconAlertErrorC, HTMLStencilElement {
    }
    var HTMLStenIconAlertErrorCElement: {
        prototype: HTMLStenIconAlertErrorCElement;
        new (): HTMLStenIconAlertErrorCElement;
    };
    interface HTMLStenIconAlertErrorCircleCElement extends Components.StenIconAlertErrorCircleC, HTMLStencilElement {
    }
    var HTMLStenIconAlertErrorCircleCElement: {
        prototype: HTMLStenIconAlertErrorCircleCElement;
        new (): HTMLStenIconAlertErrorCircleCElement;
    };
    interface HTMLStenIconsElement extends Components.StenIcons, HTMLStencilElement {
    }
    var HTMLStenIconsElement: {
        prototype: HTMLStenIconsElement;
        new (): HTMLStenIconsElement;
    };
    interface HTMLStenImageElement extends Components.StenImage, HTMLStencilElement {
    }
    var HTMLStenImageElement: {
        prototype: HTMLStenImageElement;
        new (): HTMLStenImageElement;
    };
    interface HTMLStenTestElement extends Components.StenTest, HTMLStencilElement {
    }
    var HTMLStenTestElement: {
        prototype: HTMLStenTestElement;
        new (): HTMLStenTestElement;
    };
    interface HTMLElementTagNameMap {
        "sten-icon-aa-c": HTMLStenIconAaCElement;
        "sten-icon-add": HTMLStenIconAddElement;
        "sten-icon-add-image": HTMLStenIconAddImageElement;
        "sten-icon-add-user": HTMLStenIconAddUserElement;
        "sten-icon-alert-close-collapse": HTMLStenIconAlertCloseCollapseElement;
        "sten-icon-alert-error-c": HTMLStenIconAlertErrorCElement;
        "sten-icon-alert-error-circle-c": HTMLStenIconAlertErrorCircleCElement;
        "sten-icons": HTMLStenIconsElement;
        "sten-image": HTMLStenImageElement;
        "sten-test": HTMLStenTestElement;
    }
}
declare namespace LocalJSX {
    interface StenIconAaC {
        /**
          * 传入的class名称
         */
        "classNames"?: string;
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 旋转的角度
         */
        "rotate"?: number;
        /**
          * icon 尺寸 默认 20
         */
        "size"?: number | string;
        /**
          * 是否自动旋转
         */
        "spin"?: boolean;
        /**
          * styles 传入的css样式
         */
        "styles"?: object;
    }
    interface StenIconAdd {
        /**
          * 传入的class名称
         */
        "classNames"?: string;
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 旋转的角度
         */
        "rotate"?: number;
        /**
          * icon 尺寸 默认 20
         */
        "size"?: number | string;
        /**
          * 是否自动旋转
         */
        "spin"?: boolean;
        /**
          * styles 传入的css样式
         */
        "styles"?: object;
    }
    interface StenIconAddImage {
        /**
          * 传入的class名称
         */
        "classNames"?: string;
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 旋转的角度
         */
        "rotate"?: number;
        /**
          * icon 尺寸 默认 20
         */
        "size"?: number | string;
        /**
          * 是否自动旋转
         */
        "spin"?: boolean;
        /**
          * styles 传入的css样式
         */
        "styles"?: object;
    }
    interface StenIconAddUser {
        /**
          * 传入的class名称
         */
        "classNames"?: string;
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 旋转的角度
         */
        "rotate"?: number;
        /**
          * icon 尺寸 默认 20
         */
        "size"?: number | string;
        /**
          * 是否自动旋转
         */
        "spin"?: boolean;
        /**
          * styles 传入的css样式
         */
        "styles"?: object;
    }
    interface StenIconAlertCloseCollapse {
        /**
          * 传入的class名称
         */
        "classNames"?: string;
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 旋转的角度
         */
        "rotate"?: number;
        /**
          * icon 尺寸 默认 20
         */
        "size"?: number | string;
        /**
          * 是否自动旋转
         */
        "spin"?: boolean;
        /**
          * styles 传入的css样式
         */
        "styles"?: object;
    }
    interface StenIconAlertErrorC {
        /**
          * 传入的class名称
         */
        "classNames"?: string;
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 旋转的角度
         */
        "rotate"?: number;
        /**
          * icon 尺寸 默认 20
         */
        "size"?: number | string;
        /**
          * 是否自动旋转
         */
        "spin"?: boolean;
        /**
          * styles 传入的css样式
         */
        "styles"?: object;
    }
    interface StenIconAlertErrorCircleC {
        /**
          * 传入的class名称
         */
        "classNames"?: string;
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 旋转的角度
         */
        "rotate"?: number;
        /**
          * icon 尺寸 默认 20
         */
        "size"?: number | string;
        /**
          * 是否自动旋转
         */
        "spin"?: boolean;
        /**
          * styles 传入的css样式
         */
        "styles"?: object;
    }
    interface StenIcons {
        /**
          * 传入的class名称
         */
        "classNames"?: string;
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 旋转的角度
         */
        "rotate"?: number;
        /**
          * icon 尺寸 默认 20
         */
        "size"?: number | string;
        /**
          * 是否自动旋转
         */
        "spin"?: boolean;
        /**
          * styles 传入的css样式
         */
        "styles"?: object;
    }
    interface StenImage {
        /**
          * Prop 错误文案
         */
        "errorText"?: string;
        /**
          * Prop fit 图片填充格式
         */
        "fit"?: 'none' | 'contain' | 'cover' | 'fill' | 'scale-down';
        /**
          * Prop lazy 是否懒加载
         */
        "lazy"?: boolean;
        /**
          * Prop placeholder 加载文案
         */
        "placeholder"?: string;
        /**
          * Prop src 图片链接
         */
        "src"?: string;
    }
    interface StenTest {
    }
    interface IntrinsicElements {
        "sten-icon-aa-c": StenIconAaC;
        "sten-icon-add": StenIconAdd;
        "sten-icon-add-image": StenIconAddImage;
        "sten-icon-add-user": StenIconAddUser;
        "sten-icon-alert-close-collapse": StenIconAlertCloseCollapse;
        "sten-icon-alert-error-c": StenIconAlertErrorC;
        "sten-icon-alert-error-circle-c": StenIconAlertErrorCircleC;
        "sten-icons": StenIcons;
        "sten-image": StenImage;
        "sten-test": StenTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sten-icon-aa-c": LocalJSX.StenIconAaC & JSXBase.HTMLAttributes<HTMLStenIconAaCElement>;
            "sten-icon-add": LocalJSX.StenIconAdd & JSXBase.HTMLAttributes<HTMLStenIconAddElement>;
            "sten-icon-add-image": LocalJSX.StenIconAddImage & JSXBase.HTMLAttributes<HTMLStenIconAddImageElement>;
            "sten-icon-add-user": LocalJSX.StenIconAddUser & JSXBase.HTMLAttributes<HTMLStenIconAddUserElement>;
            "sten-icon-alert-close-collapse": LocalJSX.StenIconAlertCloseCollapse & JSXBase.HTMLAttributes<HTMLStenIconAlertCloseCollapseElement>;
            "sten-icon-alert-error-c": LocalJSX.StenIconAlertErrorC & JSXBase.HTMLAttributes<HTMLStenIconAlertErrorCElement>;
            "sten-icon-alert-error-circle-c": LocalJSX.StenIconAlertErrorCircleC & JSXBase.HTMLAttributes<HTMLStenIconAlertErrorCircleCElement>;
            "sten-icons": LocalJSX.StenIcons & JSXBase.HTMLAttributes<HTMLStenIconsElement>;
            "sten-image": LocalJSX.StenImage & JSXBase.HTMLAttributes<HTMLStenImageElement>;
            "sten-test": LocalJSX.StenTest & JSXBase.HTMLAttributes<HTMLStenTestElement>;
        }
    }
}
